// PLL of the SDRAM bring-up: one 1000 MHz VCO from the 50 MHz board clock, so the same
// PLL gives the SDRAM clock (1000 / 7 = 142.857 MHz) and the core clock (1000 / 20 = 50 MHz).
//
//   outclk_0  142.857 MHz, phase 0        the controller and the self test
//   outclk_1  142.857 MHz, phase shifted  the DRAM_CLK pin (see the note below)
//   outclk_2   50.000 MHz, phase 0        the core side of the bridge (not used by the self test)
//
// The shift of outclk_1 is the one number to tune on the board: the clock the chip sees has
// to reach it so that the commands the controller launches are stable at its edge and the
// data it drives is stable at ours. 4000 ps is the same as the usual -3 ns of a 7 ns clock.
// Quartus computes the counters from these frequencies, as for an IP generated by the wizard.
`timescale 1ns/10ps
module sdram_pll (
	input  wire refclk,
	input  wire rst,
	output wire outclk_0,
	output wire outclk_1,
	output wire outclk_2,
	output wire locked
);

	altera_pll #(
		.fractional_vco_multiplier("false"),
		.reference_clock_frequency("50.0 MHz"),
		.operation_mode("direct"),
		.number_of_clocks(3),
		.output_clock_frequency0("142.857143 MHz"),
		.phase_shift0("0 ps"),
		.duty_cycle0(50),
		.output_clock_frequency1("142.857143 MHz"),
		.phase_shift1("2750 ps"),
		.duty_cycle1(50),
		.output_clock_frequency2("50.000000 MHz"),
		.phase_shift2("0 ps"),
		.duty_cycle2(50),
		.pll_type("General"),
		.pll_subtype("General")
	) altera_pll_i (
		.rst	(rst),
		.outclk	({outclk_2, outclk_1, outclk_0}),
		.locked	(locked),
		.fboutclk	( ),
		.fbclk	(1'b0),
		.refclk	(refclk)
	);

endmodule
